# Default configuration for FrogShield components

InputValidator:
  context_window: 5

RealtimeMonitor:
  sensitivity_threshold: 0.8
  initial_avg_length: 50
  behavior_monitoring_factor: 2

TextAnalysis:
  syntax_non_alnum_threshold: 0.3
  syntax_max_word_length: 50
  